export const Providers = {
  ROLES_PAGES_REPOSITORY: 'ROLES_PAGES_REPOSITORY',
  PAGES_REPOSITORY:'PAGES_REPOSITORY',
  ROLE_REPOSITORY: 'ROLE_REPOSITORY',
  USER_REPOSITORY_IMPL: 'USER_REPOSITORY_IMPL',
  ENCRYPTION: 'ENCRYPTION',
  ENV_CONFIG_SERVICE: 'ENV_CONFIG',
  MAIL_SERVICE: 'MAIL_SERVICE',
  OWNER_TYPE: 'OWNER_TYPE_REPOSITORY_IMPL',
  JWT_SERVICE: 'JWT_SERVICE',
  AUTH_SERVICE: 'AUTH_SERVICE',
  LOGGED_USER_SERVICE: 'LOGGED_USER_SERVICE',
  CNPJ_SERVICE: 'CNPJ_SERVICE,'
} as const;
