export const Providers = {
  USER_REPOSITORY_IMPL: 'USER_REPOSITORY_IMPL',
  ENCRYPTION: 'ENCRYPTION',
  ENV_CONFIG_SERVICE: 'ENV_CONFIG',
  MAIL_SERVICE: 'MAIL_SERVICE',
  OWNER_TYPE: 'OWNER_TYPE_REPOSITORY_IMPL',
} as const;
